import { commandViews } from "./generated-canvas-template/ui/command-views.mjs";

export function buildGenerationPrompt({ request, callbackUrl }) {
    const { constitution, workflow } = commandViews(request.blueprint);
    const approvalRequired = request.blueprint.setup?.requireInstallationApproval === true
        && [...(request.blueprint.setup.presets ?? []), ...(request.blueprint.setup.extensions ?? [])].length > 0;
    const steps = request.blueprint.pipeline.steps
        .map((step) => `${step.index + 1}. ${step.label}: invoke ${step.invocation}; artifact=${step.artifact.pathTemplate ?? "none"}; predecessors=${JSON.stringify(step.predecessors)}`)
        .join("\n");
    const callbackInstanceId = `generation-callback-${request.requestId}`;
    const callbackOpen = JSON.stringify({
        canvasId: "speckit-wizard",
        instanceId: callbackInstanceId,
        input: { cwd: request.workspacePath },
    });
    const generatedOpen = JSON.stringify({
        canvasId: request.metadata.extensionId,
        instanceId: `generated-handoff-${request.requestId}`,
        input: { cwd: request.workspacePath },
    });
    return [
        "Generate the project-scoped Copilot canvas described by the deterministic Spec Kit Wizard request.",
        `Request file: ${request.requestFile}`,
        `Target: ${request.target.relativeDirectory}`,
        "Report generation failures in chat: explain what failed, include the relevant error without credentials, and state any known recovery step. Do this even if the result callback cannot be delivered; do not rely on status text beside the Generate button.",
        "",
        "Required workflow (do not skip or substitute steps):",
        "1. Invoke /create-canvas for authoring guidance only. This production generation task does not authorize its runtime validation checklist or any testing.",
        "Generation boundary: create and statically check the extension, load it, report the result, then open the generated canvas once as the final user handoff and stop. Do not run tests, browser automation, smoke tests, action probes, invalid-input checks, or reserved-action checks. Do not invoke any workflow skill, execute or queue any phase (including Constitution), install components, change consent, or create sample workflow artifacts.",
        "2. Call extensions_manage with operation \"guide\" before writing extension code.",
        request.overwrite
            ? `3. Overwrite was explicitly authorized. Remove only the existing \"${request.target.relativeDirectory}\" directory, then scaffold a project canvas extension named \"${request.metadata.extensionId}\" with extensions_manage operation \"scaffold\", kind \"canvas\", location \"project\".`
            : `3. Scaffold a project canvas extension named \"${request.metadata.extensionId}\" with extensions_manage operation \"scaffold\", kind \"canvas\", location \"project\". Do not replace any existing target.`,
        `4. Run the deterministic materializer: node "${request.requestFile.replace(/request\.json$/, "materialize-template.mjs")}" --request "${request.requestFile}" --target "${request.target.relativeDirectory}".`,
        "   The materializer owns extension.mjs, pipeline.json, README.md, ui/, and the base runtime. Do not redesign or replace them.",
        "   Preserve the request metadata exactly. The Wizard derives the canvas name from the highest-priority active preset or extension; do not add a “Generated” prefix or expose generation mechanics to end users.",
        "   Preserve metadata.workflowListName exactly as the admin entered it for the collection heading (default Workflows). Do not infer, translate, lowercase, singularize, or pluralize it. Other template-owned copy is neutral: New, Current selection, Search, and deletion using the selected item's actual name. This setting never changes item identities, slugs, paths, skills, or phase input guidance.",
        approvalRequired
            ? "   Preserve the installation approval gate: only the template-owned approval panel lists this blueprint's setup.presets and setup.extensions. Do not add catalog items or destination-installed components. The runtime first performs read-only current-project installation checks. If all required contributions are already installed (including via CLI), do not request installation approval or reinstall them; continue existing configuration/skill setup only. Otherwise, before the user selects Approve and install, do not install, reconcile, reload session skills, queue a phase, or execute a phase. Never approve on the user's behalf or edit consent records. Not now installs nothing; Review installation restores the full list. Existing components remain installed and only missing components may be added. Keep the rest of the generated canvas UI and current colors exactly the same."
            : "   Preserve the implicit setup UX: normal automatic setup has no visible banner or “starting workflow” indicator. Except while the configured Constitution prerequisite blocks execution, Run phase remains available during setup, queues the requested phase behind setup, then shows only the Wizard-style spinner and “Running…” acknowledgement for 15 seconds. Chat owns ongoing progress.",
        "   Preserve setup.requireInstallationApproval exactly as captured by the Wizard. Missing or false keeps automatic setup; an empty contribution list needs no approval. Approval is template-owned, never an AI-authored configuration override.",
        "   Preserve optional projectArtifacts.constitution exactly. Its referenced command remains in the full source steps, required skills and exact phaseInputs keys, but is excluded from the numbered workflow, per-item artifacts, collection derivation and slug placement. When configured, render Constitution only in the template's compact top-level card and on-demand viewer/dialog, never below the workflow pipeline. A Constitution-only selection shows no dummy workflow. Missing descriptor means no Constitution UI or prerequisite, even if a constitution exists on disk.",
        "   Execution order is installation approval, setup/session skills, then verified Constitution, then normal phases. The server rechecks the declared artifact before all non-Constitution runs (including setup queue draining and reruns); missing/empty/template/error returns constitution_required without dispatch. Do not bypass the gate, run Constitution automatically, or treat command completion as readiness. Constitution invocation has only its captured skill and guidance, never an item, slug or feature path.",
        `   Preserve the blueprint slug contract: ${request.blueprint.runtime.userProvidesSlug ? "show an optional workflow slug field and include `slug=<user-value>` in the phase invocation only when the user supplies it" : "do not show a workflow slug field and omit `slug=` from phase invocations so the workflow infers it at runtime"}.`,
        `   Preserve the blueprint instance contract: ${constitution && !workflow.length ? "show only the project Constitution card; no dummy workflow, collection or empty stepper" : request.blueprint.runtime.multiInstance ? "show the deterministic aggregate collection of all slug-keyed workflow instances, with selected-instance phase details and a New action, including in the empty collection" : "show exactly one workflow, bind its slug once, reuse it for later phases, and never expose sibling slug directories as a collection"}.`,
        "5. Read each selected phase's effective installed .github/skills/<skillName>/SKILL.md (using its exact blueprint skillName), including preset overrides. Read blueprint source.skillPath when present as supporting context, not in place of the effective skill. Infer accepted arguments and substantive input from those instructions, not from phase names or generic examples. Do not invent commands outside the blueprint allowlist.",
        "   Customize only workflow-config.json, never executable code. workflow-adapter.mjs is now a protected template file, like extension.mjs, pipeline.json, README.md, ui/, and the base runtime.",
        "   The JSON contract is {\"version\":1,\"itemLabels\":{},\"phaseArguments\":{},\"phaseInputs\":{}}. itemLabels maps known workflow IDs to display labels. phaseArguments maps exact blueprint instanceKeys to optional {\"prefix\":\"fixed arguments\",\"suffix\":\"fixed arguments\"}. Use labels/fixed arguments only when the selected skill explicitly requires them; otherwise keep those empty maps.",
        "   Author phaseInputs for EVERY exact blueprint instanceKey: {\"label\":\"Phase input\",\"helper\":\"One concise sentence about useful content.\",\"optional\":false}. The materializer seeds neutral entries; replace them with skill-derived copy whenever the skill explains useful input. Labels are at most 80 characters; helpers are at most 240 characters, plain single-line text. Use a specific content label when supported (otherwise Phase input). Keep phase descriptions unchanged.",
        "   Include the Constitution key even though it is outside the workflow strip. For the standard core Constitution skill preserve label Guidance, helper Optional: principles to emphasize (e.g. testing, performance, UX), optional:true. If an effective override changes accepted input, derive its substantive helper and optionality from that exact skill instead. The dialog always uses Guidance and an empty native placeholder, with Cancel/Run; it has no slug or item picker.",
        "   Phase input guidance must describe ONLY substantive content: the idea, requested change, constraints, questions, or additional direction. NEVER mention supplying a slug, workflow ID, command, argument syntax, workspace, directory, folder, path, output location, or passing a location. Omit these instructions entirely, even when present in the skill, rather than paraphrasing or relocating them. Workflow slug and Writes to already explain these separately and must remain unchanged.",
        "   Set optional:true only when the effective skill explicitly supports running with no additional textbox input. Do not infer input optionality from step.optional (that means an optional phase). Distinguish information needed by the skill from information that must be typed before Run; the skill may ask in chat or read earlier artifacts. For conditional requirements, give concise content-only advice and leave optional:false. When input requirements are unclear or a skill cannot be read, retain the neutral Phase input label/helper and optional:false, and report unreadable skills as a generation caveat.",
        "   Helper text appears inside an empty textarea as native placeholder text: it disappears when the user types and returns when cleared. It is never a prefilled value or submitted as user input. The field label stays visible, with an equivalent screen-reader description but no visible helper paragraph above the textbox. No required-input markers, empty-input validation, general phase-order gating, or new input rules. The template's installation approval and configured Constitution gates still apply. Verify each phase's label/helper against its effective skill and these exclusions before validation.",
        "   Unknown keys, unknown phases, multiline fixed arguments, and slug arguments in this configuration are rejected. Never emit code, imports, expressions, templates, or callbacks. The runtime preserves user input and inserts the selected slug exactly once.",
        "   Item discovery, artifact paths, and the empty-workflow sentinel (id=\"__new__\", slug=null, isNew=true) are template-owned. Configuration cannot add/filter items, choose other artifact paths, change setup, or alter phase dispatch.",
        "   If the workflow needs behavior this schema cannot express, report generation failed with the unsupported requirement; do not modify protected files or silently discard the requirement.",
        "   Keep command order and skill invocations byte-for-byte as specified. The deterministic app exposes list_items, setup_workflow, reloadSessionSkills, run_phase, and blueprint-gated delete_workflow.",
        `6. Before loading any generated code, validate the output: node "${request.requestFile.replace(/request\.json$/, "materialize-template.mjs")}" --request "${request.requestFile}" --target "${request.target.relativeDirectory}" --validate. This checks protected code hashes, blueprint equality, and configuration schema. On failure stop and report failed; do not reload the extension. Only after validation succeeds, reload extensions with extensions_reload.`,
        `7. Inspect the extension with extensions_manage operation \"inspect\", name \"${request.metadata.extensionId}\".`,
        "8. Do not exercise the generated canvas. Do not call its actions or HTTP endpoints, including list_items, setup_workflow, reloadSessionSkills, run_phase, or delete_workflow. Read-only provider inspection in step 7 is a load-status check, not a runtime test; report a failed provider instead of exercising it. The only generated-canvas interaction permitted is the final open in step 11. Normal runtime setup-on-open behavior is unchanged, but this generation task must not drive setup, approve installation, or execute phases.",
        `9. Because reload may replace the Wizard server URL, call open_canvas with ${callbackOpen}, use the returned URL's origin and token to POST /api/generation/report. If the Wizard URL did not change, ${callbackUrl} is also valid.`,
        `10. Send JSON {\"requestId\":\"${request.requestId}\",\"state\":\"succeeded\",\"message\":\"...\"}. Success is valid only after the deterministic template, pipeline.json, workflow-config.json, and validation passed. On any failure send state \"failed\" and an \"error\" string.`,
        `11. Only after successful generation reporting, call open_canvas with ${generatedOpen} to present the new canvas to the user, then stop. Do not click controls, inspect rendered content, invoke actions, run tests, or execute phases afterward. If opening fails, report that the canvas was generated but could not be opened, include the error without credentials, and stop; do not regenerate or troubleshoot by running workflow actions.`,
        "",
        "Pipeline:",
        steps,
        "",
        `Overwrite authorized: ${request.overwrite ? "yes" : "no"}.`,
        "Do not modify the Spec Kit Wizard UI, manifests, marketplace metadata, or documentation.",
    ].join("\n");
}
