"""Candidate receipt binds every final generated byte except itself."""

import json
import shutil
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch


PACKAGE = Path(__file__).resolve().parents[2]
FIXTURES = PACKAGE / "tests" / "fixtures" / "composition"
sys.path.insert(0, str(PACKAGE / "scripts" / "lib"))

from override import prepare_override  # noqa: E402
from receipt import write_receipt  # noqa: E402
from contracts.handoff import prepare_request  # noqa: E402
from staging import atomic_json, materialize_candidate, read_json  # noqa: E402
from validation import validate_candidate  # noqa: E402


class ReceiptContracts(unittest.TestCase):
    def test_receipt_covers_final_files_and_provider_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            workspace = Path(directory)
            shutil.copytree(FIXTURES / "installed", workspace / ".specify")
            inventory = {
                "artifacts": json.loads((FIXTURES / "mixed-stack.json").read_text(encoding="utf-8")),
                "presets": json.loads((FIXTURES / "installed-presets.json").read_text(encoding="utf-8")),
                "extensions": json.loads((FIXTURES / "installed-extensions.json").read_text(encoding="utf-8")),
            }
            with patch("request._preflight"):
                request = prepare_request(
                    workspace, ["speckit.plan"], "my-canvas", "My Canvas",
                    False, inventory=inventory,
                )
            atomic_json(request.with_name("command-override-draft.json"), {"categories": {}})
            prepare_override(request)
            scaffold = PACKAGE / "tests" / "fixtures" / "scaffold"
            candidate = materialize_candidate(request, scaffold)
            path = write_receipt(request, scaffold)
            receipt = read_json(path)
            self.assertEqual(receipt["schemaVersion"], 1)
            self.assertEqual(receipt["canvasId"], "my-canvas")
            self.assertNotIn(".speckit-canvas.json", [item["path"] for item in receipt["files"]])
            self.assertEqual(len(receipt["files"]), len(validate_candidate(request, scaffold)))
            self.assertEqual(receipt["runtimeProviders"], [])
            self.assertNotIn("renderer", receipt)
            with self.assertRaisesRegex(ValueError, "already exists"):
                write_receipt(request, scaffold)
            altered = dict(receipt)
            altered["generator"] = {**receipt["generator"], "version": "invalid"}
            atomic_json(path, altered)
            with self.assertRaisesRegex(ValueError, "receipt does not match"):
                validate_candidate(request, scaffold)
            self.assertFalse((workspace / ".github" / "extensions" / "my-canvas").exists())


if __name__ == "__main__":
    unittest.main()
